on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

env:
  FLUTTER_VERSION: 3.10.6

name: Deploying on GitHub Pages

jobs:
  deploy_preview:
    name: Deploy preview versions on pull requests
    if: startsWith(github.ref, "refs/pull/")
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Setup Nix (to build libolm)
        uses: cachix/install-nix-action@v19

      - name: Build libolm
        run: |
          rm -rf assets/js
          nix build -v "git+https://gitlab.matrix.org/matrix-org/olm.git#javascript" -o assets/js
          sudo chmod 777 -R assets/js
          cd assets/js/ && mv javascript package

      - name: Build Web version
        run: ./scripts/build-web.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: "tk"
          destination_dir: "${{ github.event.pull_request.number }}"
